name: "v6_IBKR_WebAPI"
version: "1.0.0"
slug: "v6_ibkr_webapi"
description: "A complete boilerplate Python bot add-on for Home Assistant."
arch:
  - amd64
  - aarch64
startup: application
boot: auto
options:
  greeting_message: "Hello from Home Assistant!"
schema:
  greeting_message: "str"
