GRID_TAB_NAME = "TQQQ_Tracker"
FILLS_TAB_NAME = "Fills"
HEALTH_TAB_NAME = "Health"
ERRORS_TAB_NAME = "Errors"

# Grid Tab Columns (1-based index for gspread)
COL_STATUS = 3        # Column C
COL_STRATEGY = 4      # Column D - formula driven "Y"
COL_SELL_PRICE = 6    # Column F
COL_BUY_PRICE = 7     # Column G
COL_SHARES = 8        # Column H

# Special Cells
ROW_HEARTBEAT = 1
COL_HEARTBEAT = 3     # C1
ROW_CASH = 2
COL_CASH = 3          # C2
ROW_ANCHOR_ASK = 7
COL_ANCHOR_ASK = 7    # G7

# Grid boundaries
GRID_START_ROW = 7
GRID_END_ROW = 100

# Fills Tab Columns
COL_TIMESTAMP = "TIMESTAMP"
COL_EXEC_ID = "EXEC_ID"
COL_FILL_ROW_ID = "ROW_ID"
COL_FILL_TYPE = "TYPE"
COL_FILLED_PRICE = "FILLED_PRICE"
COL_FILLED_QTY = "FILLED_QTY"
COL_ORDER_ID = "ORDER_ID"
COL_PERM_ID = "PERM_ID"
COL_SYMBOL = "SYMBOL"

# Logging Headers
FILLS_HEADERS = ["TIMESTAMP", "EXEC_ID", "ROW_ID", "TYPE", "FILLED_PRICE", "FILLED_QTY", "ORDER_ID", "PERM_ID", "SYMBOL"]
HEALTH_HEADERS = [
    "TIMESTAMP", "LAST_PRICE", "OPEN_ORDERS_COUNT", "LAST_FILL_TIME", "STATUS",
    "POSITION", "MARKET_PRICE", "MARKET_VALUE", "AVG_COST",
    "NET_LIQUIDATION_VALUE"
]
ERRORS_HEADERS = ["TIMESTAMP", "ERROR_MSG"]
